version: '2'
services:
  zookeeper1:
    container_name: zookeeper1
    image: hyperledger/fabric-zookeeper
    restart: always
    environment:
      - quorumListenOnAllIPs=true
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=0.0.0.0:2888:3888 server.2=192.168.0.10:2888:3888 server.3=192.168.0.11:2888:3888
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    extra_hosts:
      - "zookeeper1:192.168.0.12"
      - "zookeeper2:192.168.0.10"
      - "zookeeper3:192.168.0.11"
      - "kafka1:192.168.0.12"
      - "kafka2:192.168.0.10"
      - "kafka3:192.168.0.11"
      - "kafka4:192.168.0.8"