version: '2'
services:
  kafka1:
    container_name: kafka1
    image: hyperledger/fabric-kafka
    restart: always
    hostname: kafka1
    environment:
      - KAFKA_MESSAGE_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_LOG_RETENTION_MS=-1
      - KAFKA_BROKER_ID=1
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=192.168.0.12:2181,192.168.0.10:2181,192.168.0.11:2181
    ports:
      - 9092:9092
    extra_hosts:
      - "zookeeper1:192.168.0.12"
      - "zookeeper2:192.168.0.10"
      - "zookeeper3:192.168.0.11"
      - "kafka1:192.168.0.12"
      - "kafka2:192.168.0.10"
      - "kafka3:192.168.0.11"
      - "kafka4:192.168.0.8"